services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: modularphp-api
    volumes:
      - ./app:/app
      - ./public:/var/www/html/public
      - ./conf/db-conf:/etc/db-conf
    networks:
      - mysql-network
    ports:
      - "8080:80"
    working_dir: /app

  mysql:
    image: mysql:8.1.0
    container_name: modularphp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: modularphp_db
      MYSQL_USER: modularphp
      MYSQL_PASSWORD: modularphp
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql-network
    ports:
      - "3306:3306"

networks:
  mysql-network:
    driver: bridge

volumes:
  mysql_data:
